# Отключение аутентификации для сервера Loki. Значение `false` означает, что доступ будет разрешен без проверки прав.
auth_enabled: false

# Конфигурация сервера Loki
server:
  # Порт, на котором сервер будет слушать HTTP-запросы
  http_listen_port: 3100

# Общая конфигурация, используемая различными компонентами Loki
common:
  # Адрес экземпляра Loki (обычно localhost или IP-адрес хоста)
  instance_addr: 127.0.0.1
  # Префикс пути для всех эндпоинтов API и веб-интерфейса
  path_prefix: /loki
  # Настройка хранения данных
  storage:
    filesystem:
      # Директория для хранения отрезков логов (chunks)
      chunks_directory: /loki/chunks
      # Директория для хранения правил (например, правил оповещений)
      rules_directory: /loki/rules
  # Фактор репликации (1 — означает, что данные не реплицируются)
  replication_factor: 1
  # Конфигурация кольца (ring), используется для распределения данных между ингестерами
  ring:
    kvstore:
      # Хранилище метаданных (inmemory — в памяти, без внешней базы данных)
      store: inmemory

# Конфигурация схемы хранения логов
schema_config:
  configs:
    # Начальная дата, с которой применяется эта схема
    - from: 2020-10-24
      # Тип хранилища для временных меток (TSDB — Time Series Database)
      store: tsdb
      # Хранилище объектов (filesystem — файловая система)
      object_store: filesystem
      # Версия схемы
      schema: v13
      # Индексная конфигурация
      index:
        # Префикс для названия индексных файлов
        prefix: index_
        # Периодичность создания новых индексных файлов
        period: 24h

# Конфигурация правил (например, для отправки уведомлений об alert'ах)
ruler:
  # URL Alertmanager'а, который будет использоваться для отправки alert'ов
  alertmanager_url: http://localhost:9093

# Конфигурация компактной (compactor) части Loki, которая отвечает за очистку и оптимизацию хранения
compactor:
  # Включение удаления старых логов по политике retention
  retention_enabled: true
  # Задержка перед удалением логов после окончания периода retention
  retention_delete_delay: 2h
  # Хранилище для запросов на удаление
  delete_request_store: filesystem

# Ограничения и политики для Loki
limits_config:
  # Период хранения логов в часах (480h = 20 дней)
  retention_period: 480h
  # Максимальное количество потоков логов на пользователя (комментарий говорит, что это ограничение закомментировано)
  # max_streams_per_user: 100000

# Конфигурация ингестера, который принимает логи и сохраняет их
ingester:
  # Алгоритм сжатия данных (snappy — быстрый алгоритм сжатия)
  chunk_encoding: snappy