http:
  routers: # ========================= ROUTERS =========================
    traefik:
      entryPoints:
        - websecure
      rule: Host(`traefik.dsaime.ru`)
      middlewares:
        - base-https-redirect
        - traefik-auth
        - sslheader
      tls:
        certResolver: cloudflare
      service: api@internal

    grafana:
      entryPoints:
        - websecure
      rule: Host(`grafana.dsaime.ru`)
      tls:
        certResolver: cloudflare
      service: grafana

    loki:
      entryPoints:
        - websecure
      rule: Host(`loki.dsaime.ru`)
      middlewares:
        - loki-auth
      tls:
        certResolver: cloudflare
      service: loki

    adminer:
      entryPoints:
        - websecure
      rule: Host(`adminer.dsaime.ru`)
      tls:
        certResolver: cloudflare
      service: adminer

    pgadmin:
      entryPoints:
        - websecure
      rule: Host(`pgadmin.dsaime.ru`)
      tls:
        certResolver: cloudflare
      service: pgadmin

    npchat-api:
      entryPoints:
        - websecure
      rule: Host(`api.npchat.dsaime.ru`)
      tls:
        certResolver: cloudflare
      service: npchat-api

    infrabot:
      entryPoints:
        - websecure
      rule: Host(`infrabot.npchat.dsaime.ru`)
      tls:
        certResolver: cloudflare
      service: infrabot

    fallback:
      entryPoints:
        - websecure
      rule: HostRegexp(`.*`)
      tls:
        certResolver: cloudflare
      service: caddy-proxy
      priority: 0 # Самый низкий приоритет

  services: # ========================= SERVICES =========================
    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000

    loki:
      loadBalancer:
        servers:
          - url: http://loki:3100

    adminer:
      loadBalancer:
        servers:
          - url: http://adminer:8080

    pgadmin:
      loadBalancer:
        servers:
          - url: http://pgadmin:80

    npchat-api:
      loadBalancer:
        servers:
          - url: http://npc.npchat:8080

    infrabot:
      loadBalancer:
        servers:
          - url: http://npc.infrabot:8080

    caddy-proxy:
      loadBalancer:
        servers:
          - url: http://caddy:80


  middlewares: # ========================= MIDDLEWARES =========================
    traefik-auth:
      basicAuth:
        usersFile: /auth/traefik # https://doc.traefik.io/traefik/middlewares/http/basicauth/

    loki-auth:
      basicAuth:
        usersFile: /auth/loki

    sslheader:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https

    base-https-redirect:
      redirectScheme:
        scheme: https