networks:
  proxy:
    external: true

services:
  traefik:
    container_name: traefik
    image: traefik:v3.3.5
    restart: on-failure:5
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./acme.json:/acme.json
      - ./traefik.yaml:/traefik.yaml:ro
      - ./config.yaml:/config.yaml:ro
      - ./auth/:/auth/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Required for Docker provider
    # environment:
    #   - CF_API_EMAIL=
    #   - CF_DNS_API_TOKEN=