networks:
  proxy:
    external: true

services:
#  https://hub.docker.com/_/adminer/
  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure:5
    networks:
      - proxy
    # ports:
    #   - "8088:8080" # http://127.0.0.1:8088/
